from django.urls import path

from .views import (
    approve_report,
    reject_report,
    get_operator_notifications,
    mark_notification_as_read,
    assign_incidence_to_employee,
    get_assigned_incidences,
    get_all_employees,
    get_completed_incidences,
    create_citizin_incidence,
    citizin_login,
    citizin_signup,
    create_department,
    delete_employee,
    delete_department,
    employee_login,
    employee_signup,
    forgot_password,
    get_departments,
    get_citizin_incidence_by_id,
    get_citizin_incidences,
    get_forworded_incidences,
    get_in_progress_incidences,
    get_incidence_by_id,
    get_incidences,
    get_new_incidences,
    get_operator_notifications,
    get_review_incidences,
    get_incidence_status_by_id,
    mark_notification_as_read,
    move_incidence_to_in_progress,
    move_incidence_to_completed,
    move_incidence_to_review,
    notify_department_region_operators,
    reset_password,
    update_employee,
    update_department,
    verify_password_otp,
)

urlpatterns = [
    path(
    "notifications/",
    get_operator_notifications,
    name="get-operator-notifications",
    ),

    path(
    "notifications/<int:notification_id>/read/",
    mark_notification_as_read,
    name="mark-notification-read",
    ),
    path(
        "incidence/<int:incidence_id>/review/",
        move_incidence_to_review,
        name="move-incidence-to-review",
    ),
    path(
        "incidence/<int:incidence_id>/in-progress/",
        move_incidence_to_in_progress,
        name="move-incidence-to-in-progress",
    ),
    path(
    "incidences/<int:report_id>/approve/",
    approve_report,
    name="approve_report",
    ),

    path(
    "incidences/<int:report_id>/reject/",
    reject_report,
    name="reject_report",
    ),
    path("incidence/<int:incidence_id>/", get_incidence_by_id, name="get-incidence-by-id"),
    path("incidence/<int:incidence_id>/status/", get_incidence_status_by_id, name="get-incidence-status-by-id"),
    path("incidence/", get_incidences, name="get-incidences"),
    path("incidence/new/", get_new_incidences, name="get-new-incidences"),
    path("incidence/assigned/", get_assigned_incidences, name="get-assigned-incidences"),
    path("incidence/review/", get_review_incidences, name="get-review-incidences"),
    path("incidence/in-progress/", get_in_progress_incidences, name="get-in-progress-incidences"),
    path("incidence/forworded/", get_forworded_incidences, name="get-forworded-incidences"),
    path("incidence/completed/", get_completed_incidences, name="get-completed-incidences"),
    path("incidence/citizin/", get_citizin_incidences, name="get-citizin-incidences"),
    path(
        "incidence/citizin/<int:incidence_id>/",
        get_citizin_incidence_by_id,
        name="get-citizin-incidence-by-id",
    ),
    path("incidence/assign/", assign_incidence_to_employee, name="assign-incidence-to-employee"),
    path("incidence/complete/", move_incidence_to_completed, name="move-incidence-to-completed"),
    path(
        "incidence/notify-operators/",
        notify_department_region_operators,
        name="notify-department-region-operators",
    ),
    path("incidence/citizin/create/", create_citizin_incidence, name="create-citizin-incidence"),
    path("department/create/", create_department, name="create-department"),
    path("department/", get_departments, name="get-departments"),
    path("department/<int:department_id>/update/", update_department, name="update-department"),
    path("department/<int:department_id>/update", update_department, name="update-department-no-slash"),
    path("department/<int:department_id>/delete/", delete_department, name="delete-department"),
    path("department/<int:department_id>/delete", delete_department, name="delete-department-no-slash"),
    path("employee/", get_all_employees, name="get-all-employees"),
    path("employee/<int:employee_id>/update/", update_employee, name="update-employee"),
    path("employee/<int:employee_id>/update", update_employee, name="update-employee-no-slash"),
    path("employee/<int:employee_id>/delete/", delete_employee, name="delete-employee"),
    path("employee/<int:employee_id>/delete", delete_employee, name="delete-employee-no-slash"),
    path("employee/login/", employee_login, name="employee-login"),
    path("employee/signup/", employee_signup, name="employee-signup"),
    path("citizin/login/", citizin_login, name="citizin-login"),
    path("citizin/signup/", citizin_signup, name="citizin-signup"),
    path("password/forgot/", forgot_password, name="forgot-password"),
    path("password/verify-otp/", verify_password_otp, name="verify-password-otp"),
    path("password/reset/", reset_password, name="reset-password"),
]
