# Generated by Django 5.0.12 on 2026-05-05 21:01

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(db_column="Name", max_length=120, unique=True),
                ),
                (
                    "logo",
                    models.FileField(
                        blank=True,
                        db_column="Logo",
                        null=True,
                        upload_to="departments/logos/",
                    ),
                ),
            ],
            options={
                "db_table": "Department",
            },
        ),
        migrations.CreateModel(
            name="Incidence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.TextField(db_column="Description")),
                (
                    "latlatitude",
                    models.DecimalField(
                        db_column="Latlatitude", decimal_places=7, max_digits=10
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        db_column="Longitude", decimal_places=7, max_digits=10
                    ),
                ),
                (
                    "location_name",
                    models.CharField(db_column="Location_Name", max_length=255),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("New", "New"),
                            ("Assigned", "Assigned"),
                            ("In_Progress", "In_Progress"),
                            ("Review", "Review"),
                            ("Forworded", "Forworded"),
                            ("Finished", "Finished"),
                        ],
                        db_column="Status",
                        default="New",
                        max_length=20,
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, db_column="Completed_At", null=True
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_column="Created_At",
                        db_index=True,
                        default=django.utils.timezone.now,
                    ),
                ),
                (
                    "dashboard_date",
                    models.DateField(
                        db_column="Dashboard_Date",
                        db_index=True,
                        default=django.utils.timezone.localdate,
                    ),
                ),
                (
                    "location_confirmation",
                    models.BooleanField(
                        db_column="Location_Confirmation", default=False
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Low", "Low"),
                            ("Medium", "Medium"),
                            ("High", "High"),
                        ],
                        db_column="Priority",
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "image_before_analysis",
                    models.FileField(
                        db_column="Image_Before_Analysis",
                        null=True,
                        upload_to="incidence/before/",
                    ),
                ),
                (
                    "image_after_analysis",
                    models.FileField(
                        blank=True,
                        db_column="Image_After_Analysis",
                        null=True,
                        upload_to="incidence/after/",
                    ),
                ),
                (
                    "ai_analysis_label_before",
                    models.CharField(
                        blank=True,
                        db_column="Ai_Analysis_Label_Before",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "ai_analysis_label_after",
                    models.CharField(
                        blank=True,
                        db_column="Ai_Analysis_Label_After",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "what_was_done",
                    models.TextField(blank=True, db_column="What_was_done", null=True),
                ),
                (
                    "department",
                    models.ForeignKey(
                        blank=True,
                        db_column="Department",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="incidences",
                        to="users.department",
                    ),
                ),
            ],
            options={
                "db_table": "Incidence",
            },
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(db_column="Name", max_length=255)),
                (
                    "national_id",
                    models.CharField(
                        db_column="National_Id", max_length=14, unique=True
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(
                        db_column="Phone_Number", max_length=11, unique=True
                    ),
                ),
                (
                    "email",
                    models.EmailField(db_column="Email", max_length=254, unique=True),
                ),
                ("password", models.CharField(db_column="Password", max_length=255)),
                (
                    "user_type",
                    models.CharField(
                        choices=[("citizin", "Citizin"), ("employee", "Employee")],
                        db_column="User_Type",
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(db_column="Is_Active", default=True)),
                (
                    "role",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("technical", "Technical"),
                            ("operator", "Operator"),
                            ("admin", "Admin"),
                            ("supervisior", "Supervisior"),
                        ],
                        db_column="Role",
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "region",
                    models.CharField(
                        blank=True, db_column="Region", max_length=120, null=True
                    ),
                ),
                (
                    "birthdate",
                    models.DateField(blank=True, db_column="Birthdate", null=True),
                ),
                (
                    "username",
                    models.CharField(
                        blank=True,
                        db_column="Username",
                        max_length=150,
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        blank=True,
                        db_column="Department",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="users",
                        to="users.department",
                    ),
                ),
            ],
            options={
                "db_table": "Users",
            },
        ),
        migrations.CreateModel(
            name="PasswordResetOTP",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(db_column="Email", max_length=254)),
                ("otp_code", models.CharField(db_column="OTP_Code", max_length=6)),
                (
                    "is_verified",
                    models.BooleanField(db_column="Is_Verified", default=False),
                ),
                ("is_used", models.BooleanField(db_column="Is_Used", default=False)),
                ("expires_at", models.DateTimeField(db_column="Expires_At")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, db_column="Created_At"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        db_column="User_Id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="password_reset_otps",
                        to="users.user",
                    ),
                ),
            ],
            options={
                "db_table": "Password_Reset_OTP",
            },
        ),
        migrations.CreateModel(
            name="OperatorNotification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "location_name",
                    models.CharField(db_column="Location_Name", max_length=255),
                ),
                (
                    "latlatitude",
                    models.DecimalField(
                        db_column="Latlatitude", decimal_places=7, max_digits=10
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        db_column="Longitude", decimal_places=7, max_digits=10
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Low", "Low"),
                            ("Medium", "Medium"),
                            ("High", "High"),
                        ],
                        db_column="Priority",
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "department_name",
                    models.CharField(db_column="Department_Name", max_length=120),
                ),
                (
                    "employee_name",
                    models.CharField(db_column="Employee_Name", max_length=255),
                ),
                (
                    "employee_email",
                    models.EmailField(db_column="Employee_Email", max_length=254),
                ),
                ("is_read", models.BooleanField(db_column="Is_Read", default=False)),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_column="Created_At", db_index=True
                    ),
                ),
                (
                    "incidence",
                    models.ForeignKey(
                        db_column="Incidence_Id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="operator_notifications",
                        to="users.incidence",
                    ),
                ),
                (
                    "operator",
                    models.ForeignKey(
                        db_column="Operator_Id",
                        limit_choices_to={"role": "operator", "user_type": "employee"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="received_operator_notifications",
                        to="users.user",
                    ),
                ),
                (
                    "sender_employee",
                    models.ForeignKey(
                        db_column="Sender_Employee_Id",
                        limit_choices_to={"user_type": "employee"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sent_operator_notifications",
                        to="users.user",
                    ),
                ),
            ],
            options={
                "db_table": "Operator_Notification",
            },
        ),
        migrations.AddField(
            model_name="incidence",
            name="assigned_employee",
            field=models.ForeignKey(
                blank=True,
                db_column="Assigned_Employee_Id",
                limit_choices_to={"user_type": "employee"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assigned_incidences",
                to="users.user",
            ),
        ),
        migrations.AddField(
            model_name="incidence",
            name="citizin",
            field=models.ForeignKey(
                db_column="Citizin_Id",
                limit_choices_to={"user_type": "citizin"},
                on_delete=django.db.models.deletion.CASCADE,
                related_name="created_incidences",
                to="users.user",
            ),
        ),
        migrations.AddConstraint(
            model_name="user",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(("user_type", "employee"), _negated=True),
                    models.Q(
                        ("role__isnull", False),
                        models.Q(("role", ""), _negated=True),
                        ("department__isnull", False),
                        ("region__isnull", False),
                        models.Q(("region", ""), _negated=True),
                    ),
                    _connector="OR",
                ),
                name="employee_required_fields",
            ),
        ),
        migrations.AddConstraint(
            model_name="user",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(("user_type", "citizin"), _negated=True),
                    models.Q(
                        ("birthdate__isnull", False),
                        ("username__isnull", False),
                        models.Q(("username", ""), _negated=True),
                    ),
                    _connector="OR",
                ),
                name="citizin_required_fields",
            ),
        ),
        migrations.AddIndex(
            model_name="passwordresetotp",
            index=models.Index(
                fields=["email", "otp_code"], name="Password_Re_Email_a18d24_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="passwordresetotp",
            index=models.Index(
                fields=["email", "is_verified", "is_used"],
                name="Password_Re_Email_c13dcd_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="operatornotification",
            index=models.Index(
                fields=["operator", "is_read", "created_at"],
                name="Operator_No_Operato_9df017_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="operatornotification",
            index=models.Index(
                fields=["incidence", "created_at"],
                name="Operator_No_Inciden_0478fb_idx",
            ),
        ),
    ]
