# Generated by Django 5.0.12 on 2026-06-21 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='incidence',
            name='duplicate',
            field=models.BooleanField(db_column='Duplicate', default=False),
        ),
        migrations.AddField(
            model_name='incidence',
            name='duplicate_similarity',
            field=models.FloatField(blank=True, db_column='Duplicate_Similarity', null=True),
        ),
        migrations.AddField(
            model_name='incidence',
            name='image_authenticity',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='incidence',
            name='image_confidence',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='incidence',
            name='priority_prediction',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='incidence',
            name='priority_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='incidence',
            name='road_confidence',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='incidence',
            name='road_prediction',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='incidence',
            name='severity_prediction',
            field=models.CharField(blank=True, db_column='Severity_Prediction', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='incidence',
            name='severity_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='incidence',
            name='trust_level',
            field=models.CharField(blank=True, db_column='Trust_Level', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='incidence',
            name='trust_score',
            field=models.FloatField(blank=True, db_column='Trust_Score', null=True),
        ),
    ]
