# Generated by Django 5.0.12 on 2026-06-21 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_incidence_duplicate_incidence_duplicate_similarity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='duplicate_rate',
            field=models.FloatField(db_column='Duplicate_Rate', default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='fake_image_ratio',
            field=models.FloatField(db_column='Fake_Image_Ratio', default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='trust_level',
            field=models.CharField(db_column='Trust_Level', default='Medium', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='trust_score',
            field=models.FloatField(db_column='Trust_Score', default=0.5),
        ),
        migrations.AddField(
            model_name='user',
            name='valid_ratio',
            field=models.FloatField(db_column='Valid_Ratio', default=0),
        ),
    ]
