# Generated by Django 5.0.12 on 2026-06-22 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_duplicate_rate_user_fake_image_ratio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incidence',
            name='status',
            field=models.CharField(choices=[('New', 'New'), ('Assigned', 'Assigned'), ('In_Progress', 'In_Progress'), ('Review', 'Review'), ('Forworded', 'Forworded'), ('Finished', 'Finished'), ('Rejected', 'Rejected')], db_column='Status', default='New', max_length=20),
        ),
    ]
