# Generated by Django 5.0.12 on 2026-06-22 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_incidence_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='incidence',
            name='forward_reason',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
